// Demo data is deliberately generated by the app's MockChainService so the
// browser can reset it without a server. This script documents and verifies
// the deterministic seed entry point used by `?demo=1`.
process.stdout.write('PaySlip DEMO_MODE seeds automatically on first load. Open http://127.0.0.1:5173/?demo=1 or use Reset Demo in the footer.\n');
